# -*- coding: utf-8 -*-
"""YT Scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGFMNtv1ZYwk44cVKBDItSIMJmQ5SQAc
"""

# Install the required library
!pip install pyngrok
!pip install youtube-transcript-api

# Import the library
from flask import Flask, request, jsonify
from youtube_transcript_api import YouTubeTranscriptApi
from pyngrok import ngrok

app = Flask(__name__)

@app.route('/webhook', methods=['POST'])
def process_url():
    try:
        # Log incoming headers and raw body for debugging
        print("Incoming Request Headers:", request.headers)
        print("Raw Request Body:", request.data.decode('utf-8'))  # Decode raw bytes to string

        # Attempt to parse JSON
        data = request.get_json(force=True, silent=True)
        if not data:
            print("Error: Request body is not valid JSON.")
            return jsonify({"error": "Request body is not valid JSON"}), 400

        print("Parsed JSON:", data)

        # Extract video_url
        video_url = data.get("video_url")
        if not video_url:
            print("Error: No video_url provided")
            return jsonify({"error": "No video_url provided"}), 400

        # Extract video ID
        video_id = video_url.split('v=')[-1].split('&')[0]
        print("Extracted Video ID:", video_id)

        # Fetch transcript
        transcript = YouTubeTranscriptApi.get_transcript(video_id)
        full_transcript = '\n'.join([item['text'] for item in transcript])
        print("Transcript fetched successfully.")

        return jsonify({"transcript": full_transcript})

    except Exception as e:
        import traceback
        traceback.print_exc()
        print("Error:", str(e))
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    # Set your Ngrok auth token
    ngrok.set_auth_token("2r8XIAIrtb5wF64sOiEVABesyhg_36bjxtoSiHXoQiXyKcjE1")
    public_url = ngrok.connect(5000)  # Expose port 5000 to the internet
    print("Ngrok URL:", public_url)
    app.run(port=5000)

"""# New Section"""